# Generated by Django 3.0.7 on 2020-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(verbose_name='')),
                ('caption', models.TextField(verbose_name='')),
                ('img', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
