# Generated by Django 3.0.7 on 2020-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(verbose_name='')),
                ('caption', models.TextField(verbose_name='')),
                ('img', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Skating',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(verbose_name='')),
                ('caption', models.TextField(verbose_name='')),
                ('img', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
    ]
