# Generated by Django 3.0.7 on 2020-07-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_dance_skating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dance',
            name='img',
        ),
        migrations.RemoveField(
            model_name='music',
            name='img',
        ),
        migrations.RemoveField(
            model_name='skating',
            name='img',
        ),
    ]
