# Generated by Django 3.0.7 on 2020-07-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200722_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
